# Generated by Django 4.2.11 on 2024-05-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='perfiles'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
